### ISSUE TITLE
How to plot reconstructed SDF as shown in Fig.1

### ISSUE THREAD

**Issue by Runsong123** [MingwuZheng/ImFace#1]
Dear Mingwu,

Congratulation for your great work.
The Fig.1 in your paper is really fancy, could you please teach me how to plot SDF(different level sets) as shown in Fig.3.

Best,
Runsong

**Comment by MingwuZheng** [comment]
Hi, Runsong. Sorry for the late reply. For Fig.3, you may refer to [this page](https://matplotlib.org/stable/gallery/images_contours_and_fields/contourf_log.html#sphx-glr-gallery-images-contours-and-fields-contourf-log-py) to plot contours of SDF.

**Comment by Runsong123** [comment]
> Hi, Runsong. Sorry for the late reply. For Fig.3, you may refer to [this page](https://matplotlib.org/stable/gallery/images_contours_and_fields/contourf_log.html#sphx-glr-gallery-images-contours-and-fields-contourf-log-py) to plot contours of SDF.

Thanks for your reply. 
I still feel curious to plot the contours of SDF in 3D view, and could you please give me some hints.

Best,
Runsong

**Comment by MingwuZheng** [comment]
I imitated [IGR](https://github.com/amosgropp/IGR) to plot 3D contours. Actually, you just need to extract different level sets by marching cubes and set the corresponding colors. For Fig.1, I use RdBu colorbar and pyrender, which can be replaced as you like.
