### ISSUE TITLE
Positional Encoding

### ISSUE THREAD

**Issue by rmraaron** [MingwuZheng/ImFace#10]
Hi,

Thanks for your great work. It's really cool. There is one experimental detail that I felt a little confused about. Regarding the Positional Encoding, I noticed in the paper and supplementary materials that it was mentioned as being used, but when I checked the codes, it did not seem to be used during training. I'm not sure if I misunderstood something, so I really look forward to hearing from you and would appreciate it. 

Thank you. Have a nice day!

**Comment by MingwuZheng** [comment]
Hi, it's an optional trick. Using PE will slightly improve the representation performance, but also causes a slowdown in training. You can choose depending on the specific situation.

**Comment by rmraaron** [comment]
Thank you for your reply. I'm closing this issue.
