### ISSUE TITLE
Custom Data - Input

### ISSUE THREAD

**Issue by alchemician** [MingwuZheng/ImFace#13]
Really great work! Was just wondering how to replicate this for custom data? (our own monocular videos)

**Comment by MingwuZheng** [comment]
Hi! We recommend checking out our recent work, [NeuFace (CVPR 2023)](https://github.com/aejion/NeuFace), which provides guidance on using ImFace for reconstructing appearances from images. Additionally, for details on how to apply the implicit model to videos, consider exploring related monocular-video-based projects like [I M Avatar](https://github.com/zhengyuf/IMavatar).
