### ISSUE TITLE
facescape datasets

### ISSUE THREAD

**Issue by zhou431496** [MingwuZheng/ImFace#15]
请问选择哪个facescape数据集
![image](https://github.com/MingwuZheng/ImFace/assets/103013400/22a72e64-a255-4f8a-ba77-9b31e50a2668)

**Comment by aejion** [comment]
我们使用的Topologically uniformed Model(TU model)数据集训练的ImFace以及ImFace++,关于具体的使用细节，请参考论文中的实现细节。

**Comment by zhou431496** [comment]
如果我们只是想测试我们的数据，还需要这些数据嘛

**Comment by aejion** [comment]
如果只是测试ImFace，只需要提供你们的测试数据即可（mesh点云，法向量，sdf值），但是需要测试数据对齐到facescape的数据空间中，并使用我们的data_preprocess中的代码对数据进行裁剪，具体测试方式请参考readme中关于fit with one 3d sample中的说明。

**Comment by zhou431496** [comment]
我们只有图像数据，可以测试嘛

**Comment by aejion** [comment]
ImFace以及ImFace++是对三维人脸几何的建模，目前还没有对纹理进行建模，所以只能使用三维人脸几何数据进行测试。

**Comment by zhou431496** [comment]
谢谢啦
