### ISSUE TITLE
What is the 'id2idx.json' and 'exp2idx.json'

### ISSUE THREAD

**Issue by theFoxofSky** [MingwuZheng/ImFace#9]

**Comment by YiChenCityU** [comment]
Have you find these two files?

**Comment by aejion** [comment]
Sorry about that. We have updated these two files at [trained model](https://drive.google.com/drive/folders/1wKvWZHhuLO6ISc0jML8DfM_u4de2m2-y).

**Comment by YiChenCityU** [comment]
Great! Thanks very much.
